### ISSUE TITLE
Doesn't take ABNF case-insensitivity into account

### ISSUE THREAD

**Issue by timmc** [rpinchbeck/Abnf-To-Antlr#1]
You may be startled to learn, as I was, that ABNF defines string literals as case-insensitive. The ABNF grammar `LETTER = "A"` should match inputs `A` or `a`, but Abnf-To-Antlr produces the following grammar:

```
chara : CAP_A;
CAP_A : 'A';
```

Since ANTLR is case-sensitive, this will only match input `A`. It would be great if you could expand this tool to generate both upper and lowercase variants for alphabetics.

(Apologies if this has already been fixed; I'm basing this report on the output of http://www.bobpinchbeck.com/abnf_to_antlr/Default.aspx)

By the way, this is a lovely tool. Thank you for writing it! I'm currently using it to make a URL parser library compliant with RFCs 3986, 5234, and 6874.

----

Reference: [RFC 5234 page 5](https://tools.ietf.org/html/rfc5234#page-5):

> NOTE:
>
> ABNF strings are case insensitive and the character set for these
> strings is US-ASCII.  
> [...]  
> To specify a rule that is case sensitive, specify the characters
> individually.
>
> For example:
>
> rulename    =  %d97 %d98 %d99  
> [...]

**Comment by rpinchbeck** [comment]
Nice catch... I will take a look.

And, thanks!

**Comment by rpinchbeck** [comment]
Fixed.

**Comment by timmc** [comment]
Great, I can confirm the fix! Thank you again.
