### ISSUE TITLE
Online conversion tool seems to be broken

### ISSUE THREAD

**Issue by lukeswindale** [rpinchbeck/Abnf-To-Antlr#5]
Sorry for raising an issue here, but your online tool seems to be broken (http://www.robertpinchbeck.com/abnf_to_antlr/Default.aspx). Even trying a simple, single-line, ABNF to ANTLR conversion results in a server error.

### Example
`SP = %x20 ; space`

![image](https://user-images.githubusercontent.com/9543028/52598746-755b2d00-2ea2-11e9-8db3-0600aa8cc9bd.png)

**Comment by lukeswindale** [comment]
Seems to be working again

**Comment by rpinchbeck** [comment]
I didn't change anything on the web server, so not sure what happened.  Glad it is working now.  There is also an [app](https://github.com/rpinchbeck/Abnf-To-Antlr/releases/tag/1.5.1) with the same interface that you can use offline.
