### ISSUE TITLE
ODATA 4.0 abnf is ambigous?

### ISSUE THREAD

**Issue by oel-rmt-se** [rpinchbeck/Abnf-To-Antlr#7]
Hi @rpinchbeck 
I tried your tool on the official ODATA version 4.0 abnf file (attached). There seems to be something wrong with the abnf grammar att this rule

count = '/$count'

The tool throws an 
  "Unexpected node type encountered."

and the node value at that point is
{<unexpected: [@1925,6444:6444='/',<56>,158:9], resync=/>}

Can you tell if this is because the ODATA grammar is ambigous?

Thanks for the tool,
Orjan
[odata-abnf-construction-rules-4.0.txt](https://github.com/rpinchbeck/Abnf-To-Antlr/files/3763709/odata-abnf-construction-rules-4.0.txt)

**Comment by rpinchbeck** [comment]
Added support for case-sensitive single-quoted strings per [RFC 7405](https://tools.ietf.org/html/rfc7405) and [Errata 5334](https://www.rfc-editor.org/errata/eid5334)
